// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OverwatchApplication.Models;

#nullable disable

namespace OverwatchApplication.Migrations
{
    [DbContext(typeof(OverwatchContext))]
    [Migration("20251118222009_intialCreate")]
    partial class intialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OverwatchApplication.Models.Ability", b =>
                {
                    b.Property<int>("AbilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbilityID"));

                    b.Property<float>("Cooldown")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeroID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AbilityID");

                    b.HasIndex("HeroID");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            AbilityID = 1,
                            Cooldown = 0f,
                            Description = "Twin automatic pistols with rapid fire.",
                            HeroID = 1,
                            Name = "Pulse Pistols",
                            Type = 0
                        },
                        new
                        {
                            AbilityID = 2,
                            Cooldown = 3f,
                            Description = "Teleport a short distance in the direction you're moving.",
                            HeroID = 1,
                            Name = "Blink",
                            Type = 2
                        },
                        new
                        {
                            AbilityID = 3,
                            Cooldown = 0f,
                            Description = "A large melee weapon that deals sweeping melee damage.",
                            HeroID = 2,
                            Name = "Rocket Hammer",
                            Type = 0
                        },
                        new
                        {
                            AbilityID = 4,
                            Cooldown = 0f,
                            Description = "Hold a large energy shield to protect allies.",
                            HeroID = 2,
                            Name = "Barrier Field",
                            Type = 2
                        });
                });

            modelBuilder.Entity("OverwatchApplication.Models.Hero", b =>
                {
                    b.Property<int>("HeroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroID"));

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyToMaster")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeroID");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            HeroID = 1,
                            CountryOfOrigin = "United Kingdom",
                            Description = "Time-jumping, high-mobility damage hero.",
                            DifficultyToMaster = 3,
                            Gender = "Female",
                            ImageURL = "/images/tracer.png",
                            Name = "Tracer",
                            Role = 1,
                            WeaponType = "Pulse Pistols"
                        },
                        new
                        {
                            HeroID = 2,
                            CountryOfOrigin = "Germany",
                            Description = "Armored knight with a massive barrier shield.",
                            DifficultyToMaster = 2,
                            Gender = "Male",
                            ImageURL = "/images/reinhardt.png",
                            Name = "Reinhardt",
                            Role = 0,
                            WeaponType = "Rocket Hammer"
                        });
                });

            modelBuilder.Entity("OverwatchApplication.Models.HeroNote", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("HeroID")
                        .HasColumnType("int");

                    b.Property<float>("HoursPlayed")
                        .HasColumnType("real");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NoteID");

                    b.HasIndex("HeroID");

                    b.HasIndex("UserID");

                    b.ToTable("HeroNotes");

                    b.HasData(
                        new
                        {
                            NoteID = 1,
                            Content = "Practice aiming while blinking.",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeroID = 1,
                            HoursPlayed = 5f,
                            UserID = 1
                        },
                        new
                        {
                            NoteID = 2,
                            Content = "Use Barrier Field to protect the team when pushing choke points.",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeroID = 2,
                            HoursPlayed = 3f,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("OverwatchApplication.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "playerone@example.com",
                            PasswordHash = "hashedpassword123",
                            UserName = "PlayerOne"
                        });
                });

            modelBuilder.Entity("OverwatchApplication.Models.Ability", b =>
                {
                    b.HasOne("OverwatchApplication.Models.Hero", "Hero")
                        .WithMany("Abilities")
                        .HasForeignKey("HeroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("OverwatchApplication.Models.HeroNote", b =>
                {
                    b.HasOne("OverwatchApplication.Models.Hero", "Hero")
                        .WithMany("Notes")
                        .HasForeignKey("HeroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OverwatchApplication.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OverwatchApplication.Models.Hero", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("OverwatchApplication.Models.User", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
